import type { HabitatInfo } from "./Habitats";

export type BirdCard = {
  id: number;
  commonName: string;
  scientificName: string;
  expansion: string;
  color: string;
  powerCategory: string | null;
  powerText: string;
  predator: string | null;
  flocking: string | null;
  bonusCard: string;
  victoryPoints: number;
  nestType: string;
  eggCapacity: number;
  wingspan: string;
  habitats: HabitatInfo;
  invertebrate: number | null;
  seed: number | null;
  fish: number | null;
  fruit: number | null;
  rodent: number | null;
  nectar: number | null;
  wildFood: number | null;
  slashFoodCost: number | null;
  starFoodCost: number | null;
  totalFoodCost: number;
  anatomist: string | null;
  cartographer: string | null;
  historian: string | null;
  photographer: string | null;
  backyardBirder: string | null;
  birdBander: string | null;
  birdCounter: string | null;
  birdFeeder: string | null;
  dietSpecialist: string | null;
  enclosureBuilder: string | null;
  falconer: string | null;
  fisheryManager: string | null;
  foodWebExpert: string | null;
  forester: string | null;
  largeBirdSpecialist: string | null;
  nestBoxBuilder: string | null;
  omnivoreExpert: string | null;
  passerineSpecialist: string | null;
  platformBuilder: string | null;
  prairieManager: string | null;
  rodentologist: string | null;
  viticulturalist: string | null;
  wetlandScientist: string | null;
  wildlifeGardener: string | null;
  caprimulgiformSpecialist: string | null;
  smallClutchSpecialist: string | null;
  endangeredSpeciesProtector: string | null;
  beakPointingLeft: string | null;
  beakPointingRight: string | null;
  note: string;
  rulings: any[];
  additionalRulings: {
    text: string;
    source: string;
  }[];
};
